### ISSUE TITLE
postgres.yml fails with docker compose

### ISSUE THREAD

**Issue by developeer** [authzed/examples#14]
I am running docker 24.0.6 and the postgres.yml on ubuntu 22.04.
I can't connect to localhost:8080  I am using authzed/spicedb:latest and latest-debug.
The browser gets a connection reset error.
I tried v1.24.0-debug same result
I tried v1.23.0-debug and it worked. I was able to connect from browser.

Something has changed that causes a connection reset.  I tried all 3 browsers (edge,chrome,firefox) which same result on each test.  Worked on 1.23.0 and failed on 1.24.0 and 1.25.0.

**Comment by developeer** [comment]
THank you.  Are there any other parts of the example repo that should also be removed/or modified based on functionality change?

**Comment by vroldanbet** [comment]
No further changes needed after the dashboard removal
